/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Returns 200 OK as long as the server can respond.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server is alive. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LivenessResponse"];
                    };
                };
                /** @description Method not allowed. */
                405: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Checks database connectivity. Returns 200 OK when healthy,
         *     503 Service Unavailable when degraded.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All checks pass. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadinessResponse"];
                    };
                };
                /** @description Method not allowed. */
                405: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
                /** @description One or more checks failed. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plugin diagnostics
         * @description Returns core and loader readiness plus plugin counts.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Diagnostics report. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiagnosticsReport"];
                    };
                };
                /** @description Method not allowed. */
                405: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate as the single owner
         * @description Requires a CSRF token (X-CSRF-Token header + csrf_token cookie).
         *     Rate-limited to 5 attempts per minute per IP.
         *     Sets doublangu_session cookie on success.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Owner password. */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Login successful. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Invalid JSON request body. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
                /** @description Invalid password. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
                /** @description Missing or invalid CSRF token. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
                /** @description Method not allowed. */
                405: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
                /** @description Rate limited. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
                /** @description Session or CSRF refresh failure. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bootstrap browser CSRF protection
         * @description Issues the same-origin csrf_token cookie required by login and logout.
         *     The token is read by the browser and echoed in X-CSRF-Token.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CSRF cookie issued. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OKResponse"];
                    };
                };
                /** @description Method not allowed. */
                405: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
                /** @description CSRF bootstrap failure. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the current session
         * @description Requires the same CSRF cookie/header pair as login. Deletes the session
         *     from the database and clears the cookie after CSRF validation.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout complete. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OKResponse"];
                    };
                };
                /** @description Missing or invalid CSRF token. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
                /** @description Method not allowed. */
                405: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
                /** @description Session deletion failure. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check session validity
         * @description Returns whether the current doublangu_session cookie is valid.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session status. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            authenticated?: boolean;
                        };
                    };
                };
                /** @description Method not allowed. */
                405: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ui/contributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read enabled UI plugin contributions
         * @description Requires an authenticated owner session.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Versioned plugin contribution snapshot. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description Owner session required. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
                /** @description Method not allowed. */
                405: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
                /** @description Contribution registry failure. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all libraries
         * @description Returns an empty array when no libraries exist.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Library list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Library"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                405: components["responses"]["MethodNotAllowed"];
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        /** Create a library */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LibraryCreate"];
                };
            };
            responses: {
                /** @description Library created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Library"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                405: components["responses"]["MethodNotAllowed"];
                500: components["responses"]["Internal"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a library */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Library record. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Library"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                405: components["responses"]["MethodNotAllowed"];
                500: components["responses"]["Internal"];
            };
        };
        /** Update a library */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LibraryUpdate"];
                };
            };
            responses: {
                /** @description Library updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Library"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                405: components["responses"]["MethodNotAllowed"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["Internal"];
            };
        };
        post?: never;
        /** Delete a library */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Library deleted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OKResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                405: components["responses"]["MethodNotAllowed"];
                500: components["responses"]["Internal"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/libraries/{id}/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List works in a library */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Work list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Work"][];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                405: components["responses"]["MethodNotAllowed"];
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        /** Create a work in a library */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkCreate"];
                };
            };
            responses: {
                /** @description Work created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Work"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                405: components["responses"]["MethodNotAllowed"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["Internal"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/works/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a work */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Work record. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Work"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                405: components["responses"]["MethodNotAllowed"];
                500: components["responses"]["Internal"];
            };
        };
        /** Update a work */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkUpdate"];
                };
            };
            responses: {
                /** @description Work updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Work"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                405: components["responses"]["MethodNotAllowed"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["Internal"];
            };
        };
        post?: never;
        /** Delete a work */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Work deleted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OKResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                405: components["responses"]["MethodNotAllowed"];
                500: components["responses"]["Internal"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/works/{id}/editions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List editions in a work */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Edition list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Edition"][];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                405: components["responses"]["MethodNotAllowed"];
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        /** Create an edition in a work */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EditionCreate"];
                };
            };
            responses: {
                /** @description Edition created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Edition"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                405: components["responses"]["MethodNotAllowed"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["Internal"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an edition */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Edition record. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Edition"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                405: components["responses"]["MethodNotAllowed"];
                500: components["responses"]["Internal"];
            };
        };
        /** Update an edition */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EditionUpdate"];
                };
            };
            responses: {
                /** @description Edition updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Edition"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                405: components["responses"]["MethodNotAllowed"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["Internal"];
            };
        };
        post?: never;
        /** Delete an edition */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Edition deleted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OKResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                405: components["responses"]["MethodNotAllowed"];
                500: components["responses"]["Internal"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/editions/{id}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List chapters in an edition */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Chapter list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Chapter"][];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                405: components["responses"]["MethodNotAllowed"];
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        /** Create a chapter in an edition */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChapterCreate"];
                };
            };
            responses: {
                /** @description Chapter created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Chapter"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                405: components["responses"]["MethodNotAllowed"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["Internal"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chapters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a chapter */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Chapter record. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Chapter"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                405: components["responses"]["MethodNotAllowed"];
                500: components["responses"]["Internal"];
            };
        };
        /** Update a chapter */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChapterUpdate"];
                };
            };
            responses: {
                /** @description Chapter updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Chapter"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                405: components["responses"]["MethodNotAllowed"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["Internal"];
            };
        };
        post?: never;
        /** Delete a chapter */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Chapter deleted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OKResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                405: components["responses"]["MethodNotAllowed"];
                500: components["responses"]["Internal"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chapters/{id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List source assets in a chapter */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Source asset list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SourceAsset"][];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                405: components["responses"]["MethodNotAllowed"];
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        /** Create a source asset in a chapter */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SourceAssetCreate"];
                };
            };
            responses: {
                /** @description Source asset created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SourceAsset"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                405: components["responses"]["MethodNotAllowed"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["Internal"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a source asset */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Source asset record. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SourceAsset"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                405: components["responses"]["MethodNotAllowed"];
                500: components["responses"]["Internal"];
            };
        };
        /** Update a source asset */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SourceAssetUpdate"];
                };
            };
            responses: {
                /** @description Source asset updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SourceAsset"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                405: components["responses"]["MethodNotAllowed"];
                409: components["responses"]["Conflict"];
                500: components["responses"]["Internal"];
            };
        };
        post?: never;
        /** Delete a source asset */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Source asset deleted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OKResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                405: components["responses"]["MethodNotAllowed"];
                500: components["responses"]["Internal"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download media bytes
         * @description Returns the content-addressed blob for a source asset. Supports
         *     byte-range requests (Range header), conditional requests
         *     (If-None-Match), and ETag based on SHA-256 digest.
         *     When X-Accel-Redirect is configured the server returns an internal
         *     redirect header instead of streaming bytes directly.
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example bytes=0-1023 */
                    Range?: components["schemas"]["SingleByteRange"];
                    "If-None-Match"?: components["schemas"]["ConditionalETag"];
                };
                path: {
                    /** @description Source asset ULID. */
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Full media bytes. */
                200: {
                    headers: {
                        ETag?: components["schemas"]["StrongSHA256ETag"];
                        "Content-Type"?: components["schemas"]["MediaType"];
                        "Accept-Ranges"?: components["schemas"]["ByteRangeUnit"];
                        "Content-Length"?: components["schemas"]["ByteLength"];
                        /** @description Optional opaque internal redirect location. */
                        "X-Accel-Redirect"?: components["schemas"]["InternalRedirectURI"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description Partial content (byte range). */
                206: {
                    headers: {
                        ETag?: components["schemas"]["StrongSHA256ETag"];
                        "Content-Type"?: components["schemas"]["MediaType"];
                        "Accept-Ranges"?: components["schemas"]["ByteRangeUnit"];
                        "Content-Range"?: components["schemas"]["ContentByteRange"];
                        "Content-Length"?: components["schemas"]["ByteLength"];
                        /** @description Optional opaque internal redirect location. */
                        "X-Accel-Redirect"?: components["schemas"]["InternalRedirectURI"];
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not modified (If-None-Match). */
                304: {
                    headers: {
                        ETag?: components["schemas"]["StrongSHA256ETag"];
                        "Content-Type"?: components["schemas"]["MediaType"];
                        "Accept-Ranges"?: components["schemas"]["ByteRangeUnit"];
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                405: components["responses"]["MethodNotAllowed"];
                /** @description Range not satisfiable. */
                416: {
                    headers: {
                        ETag?: components["schemas"]["StrongSHA256ETag"];
                        "Content-Type"?: components["schemas"]["MediaType"];
                        "Accept-Ranges"?: components["schemas"]["ByteRangeUnit"];
                        "Content-Range"?: components["schemas"]["ContentByteRange"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIError"];
                    };
                };
                500: components["responses"]["Internal"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Media metadata (no body)
         * @description Same headers as GET without the response body.
         */
        head: {
            parameters: {
                query?: never;
                header?: {
                    Range?: components["schemas"]["SingleByteRange"];
                    "If-None-Match"?: components["schemas"]["ConditionalETag"];
                };
                path: {
                    id: components["schemas"]["ULID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Media metadata. */
                200: {
                    headers: {
                        ETag?: components["schemas"]["StrongSHA256ETag"];
                        "Content-Type"?: components["schemas"]["MediaType"];
                        "Accept-Ranges"?: components["schemas"]["ByteRangeUnit"];
                        "Content-Length"?: components["schemas"]["ByteLength"];
                        /** @description Optional opaque internal redirect location. */
                        "X-Accel-Redirect"?: components["schemas"]["InternalRedirectURI"];
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Partial media metadata. */
                206: {
                    headers: {
                        ETag?: components["schemas"]["StrongSHA256ETag"];
                        "Content-Type"?: components["schemas"]["MediaType"];
                        "Accept-Ranges"?: components["schemas"]["ByteRangeUnit"];
                        "Content-Range"?: components["schemas"]["ContentByteRange"];
                        "Content-Length"?: components["schemas"]["ByteLength"];
                        /** @description Optional opaque internal redirect location. */
                        "X-Accel-Redirect"?: components["schemas"]["InternalRedirectURI"];
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not modified (If-None-Match). */
                304: {
                    headers: {
                        ETag?: components["schemas"]["StrongSHA256ETag"];
                        "Content-Type"?: components["schemas"]["MediaType"];
                        "Accept-Ranges"?: components["schemas"]["ByteRangeUnit"];
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                405: components["responses"]["MethodNotAllowed"];
                /** @description Range not satisfiable. */
                416: {
                    headers: {
                        ETag?: components["schemas"]["StrongSHA256ETag"];
                        "Content-Type"?: components["schemas"]["MediaType"];
                        "Accept-Ranges"?: components["schemas"]["ByteRangeUnit"];
                        "Content-Range"?: components["schemas"]["ContentByteRange"];
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                500: components["responses"]["Internal"];
            };
        };
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIError: {
            /** @description Human-readable error message. */
            error: string;
            /** @description Versioned machine-readable error code (for example v1.csrf_error). */
            code: string;
        };
        /** @description Canonical uppercase Crockford ULID. */
        ULID: string;
        /** @description Lowercase hexadecimal SHA-256 digest. */
        SHA256: string;
        /** @description One HTTP byte range; multiple ranges are not accepted. */
        SingleByteRange: string;
        /** @description If-None-Match input; strong, weak, list, and wildcard forms are accepted. */
        ConditionalETag: string;
        /** @description Strong quoted ETag derived from the lowercase SHA-256 digest. */
        StrongSHA256ETag: string;
        /** @description Stored source-asset media value returned verbatim as Content-Type; production does not enforce MIME type/subtype structure. */
        MediaType: string;
        /** @enum {string} */
        ByteRangeUnit: "bytes";
        /** Format: int64 */
        ByteLength: number;
        ContentByteRange: string;
        /** @description Opaque validated same-origin internal redirect URI, never a filesystem path. */
        InternalRedirectURI: string;
        /** @description BCP-47 syntactic pre-check only. Canonical acceptance and normalization
         *     are decided by the production BCP-47 parser.
         *      */
        LanguageTag: string;
        /**
         * Format: int64
         * @description Non-negative timing value; when start_ms and end_ms coexist, end_ms must be at least start_ms.
         */
        Milliseconds: number;
        OKResponse: {
            ok: boolean;
        };
        LivenessResponse: {
            /** @enum {string} */
            status: "ok";
        };
        ReadinessResponse: {
            /** @enum {string} */
            status: "ok";
            checks?: {
                [key: string]: string;
            };
            database?: string;
        };
        DiagnosticsReport: {
            core_ready?: boolean;
            loader_ready?: boolean;
            schema_available?: boolean;
            registry_state?: string;
            plugin_count?: number;
            registration_count?: number;
            plugin_ids?: string[];
        };
        LoginResponse: {
            ok?: boolean;
        };
        Library: {
            id: components["schemas"]["ULID"];
            name: string;
            source_language: components["schemas"]["LanguageTag"];
            target_language: components["schemas"]["LanguageTag"];
            description?: string;
            /** @description ISO 8601 UTC */
            created_at: string;
            /** @description ISO 8601 UTC */
            updated_at: string;
        };
        LibraryCreate: {
            name: string;
            source_language: components["schemas"]["LanguageTag"];
            target_language: components["schemas"]["LanguageTag"];
            description?: string;
        };
        LibraryUpdate: {
            name?: string;
            source_language?: components["schemas"]["LanguageTag"];
            target_language?: components["schemas"]["LanguageTag"];
            description?: string;
        };
        Work: {
            id: components["schemas"]["ULID"];
            library_id: components["schemas"]["ULID"];
            title: string;
            author: string;
            kind: string;
            source_url?: string;
            created_at: string;
            updated_at: string;
        };
        WorkCreate: {
            title: string;
            author?: string;
            kind: string;
            source_url?: string;
        };
        WorkUpdate: {
            library_id?: components["schemas"]["ULID"];
            title?: string;
            author?: string;
            kind?: string;
            source_url?: string;
        };
        Edition: {
            id: components["schemas"]["ULID"];
            work_id: components["schemas"]["ULID"];
            name: string;
            language: components["schemas"]["LanguageTag"];
            format: string;
            created_at: string;
            updated_at: string;
        };
        EditionCreate: {
            name: string;
            language: components["schemas"]["LanguageTag"];
            format: string;
        };
        EditionUpdate: {
            work_id?: components["schemas"]["ULID"];
            name?: string;
            language?: components["schemas"]["LanguageTag"];
            format?: string;
        };
        Chapter: {
            id: components["schemas"]["ULID"];
            edition_id: components["schemas"]["ULID"];
            title: string;
            chapter_number: number;
            start_ms: components["schemas"]["Milliseconds"];
            end_ms: components["schemas"]["Milliseconds"];
            duration_ms: components["schemas"]["Milliseconds"];
            created_at: string;
            updated_at: string;
        };
        ChapterCreate: {
            title: string;
            chapter_number: number;
            start_ms: components["schemas"]["Milliseconds"];
            end_ms: components["schemas"]["Milliseconds"];
            duration_ms: components["schemas"]["Milliseconds"];
        };
        ChapterUpdate: {
            edition_id?: components["schemas"]["ULID"];
            title?: string;
            chapter_number?: number;
            start_ms?: components["schemas"]["Milliseconds"];
            end_ms?: components["schemas"]["Milliseconds"];
            duration_ms?: components["schemas"]["Milliseconds"];
        };
        SourceAsset: {
            id: components["schemas"]["ULID"];
            chapter_id: components["schemas"]["ULID"];
            url: string;
            mime_type: string;
            /** Format: int64 */
            size_bytes: number;
            sha256_hash: components["schemas"]["SHA256"];
            start_ms?: components["schemas"]["Milliseconds"];
            end_ms?: components["schemas"]["Milliseconds"];
            duration_ms?: components["schemas"]["Milliseconds"];
            created_at: string;
            updated_at: string;
        };
        SourceAssetCreate: {
            url: string;
            mime_type: string;
            /** Format: int64 */
            size_bytes: number;
            sha256_hash: components["schemas"]["SHA256"];
            start_ms?: components["schemas"]["Milliseconds"];
            end_ms?: components["schemas"]["Milliseconds"];
            duration_ms?: components["schemas"]["Milliseconds"];
        };
        SourceAssetUpdate: {
            chapter_id?: components["schemas"]["ULID"];
            url?: string;
            mime_type?: string;
            /** Format: int64 */
            size_bytes?: number;
            sha256_hash?: components["schemas"]["SHA256"];
            start_ms?: components["schemas"]["Milliseconds"];
            end_ms?: components["schemas"]["Milliseconds"];
            duration_ms?: components["schemas"]["Milliseconds"];
        };
    };
    responses: {
        /** @description Validation error. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Authentication required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Missing or invalid CSRF token. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Foreign-key or uniqueness constraint violated. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Unexpected server failure. */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Method not allowed. */
        MethodNotAllowed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
