import {
	getDictionaryEntry,
	getDictionaryEntryById,
	startDictionaryExplore,
	type DictionaryDocument,
	type DictionaryStatusEnvelope
} from '$lib/api/client';

export type ExplorePhase = 'checking' | 'queued' | 'generating' | 'ready' | 'failed';

export type ExploreState = {
	phase: ExplorePhase;
	entryId: string;
	jobId: string;
	runId: string;
	document: DictionaryDocument | null;
	errorCode: string;
	generationErrorCode: string;
};

export type ExploreRef = { occurrenceId?: string; annotationId?: string };

export type ExploreControllerOptions = {
	lookup: typeof getDictionaryEntry;
	start: typeof startDictionaryExplore;
	poll: typeof getDictionaryEntryById;
	pollIntervalMs?: number;
	onChange: (state: ExploreState) => void;
};

export const initialExploreState: ExploreState = {
	phase: 'checking',
	entryId: '',
	jobId: '',
	runId: '',
	document: null,
	errorCode: '',
	generationErrorCode: ''
};

/**
 * One Explore subject's durable state machine. An explicit open performs the
 * read-only lookup first and only then may enqueue generation; polling runs
 * only while pending and stops on close, subject change, or a terminal
 * state. Every response carries the request identity it was opened with, so
 * a stale response after a subject switch or close is discarded and no poll
 * outlives the panel. Closing never cancels an already requested durable job.
 */
export function createExploreController(options: ExploreControllerOptions) {
	const pollIntervalMs = options.pollIntervalMs ?? 1500;
	let generation = 0;
	let timer: ReturnType<typeof setTimeout> | undefined;
	let state: ExploreState = { ...initialExploreState };

	function emit(next: Partial<ExploreState>): void {
		state = { ...state, ...next };
		options.onChange(state);
	}

	function clearTimer(): void {
		if (timer) clearTimeout(timer);
		timer = undefined;
	}

	function adopt(envelope: DictionaryStatusEnvelope): void {
		const status = envelope.status ?? 'missing';
		if (status === 'ready' && envelope.document) {
			emit({ phase: 'ready', entryId: envelope.entry_id ?? '', jobId: envelope.job_id ?? '', runId: envelope.run_id ?? '', document: envelope.document, errorCode: '', generationErrorCode: '' });
			return;
		}
		if (status === 'failed') {
			// A failed replacement keeps the saved document on screen; a
			// failed initial generation has none to keep.
			emit({ phase: 'failed', entryId: envelope.entry_id ?? '', jobId: envelope.job_id ?? '', runId: envelope.run_id ?? '', errorCode: envelope.error_code ?? '', generationErrorCode: envelope.generation_error_code ?? '' });
			return;
		}
		if (status === 'missing') {
			// The POST answered missing while another tab raced us; keep
			// waiting on the entry it reported or stop without polling.
			emit({ phase: 'checking' });
			return;
		}
		// queued or generating: poll by entry id while expanded, keeping
		// any saved document visible until the replacement commits.
		emit({
			phase: status === 'generating' ? 'generating' : 'queued',
			entryId: envelope.entry_id ?? '',
			jobId: envelope.job_id ?? '',
			runId: envelope.run_id ?? '',
			errorCode: '',
			generationErrorCode: ''
		});
		schedulePoll(envelope.entry_id ?? '');
	}

	function schedulePoll(entryId: string): void {
		if (!entryId) return;
		clearTimer();
		timer = setTimeout(() => {
			timer = undefined;
			const identity = generation;
			options
				.poll(entryId)
				.then((envelope) => {
					if (identity !== generation) return; // superseded by close/subject switch
					adopt(envelope);
				})
				.catch(() => {
					if (identity !== generation) return;
					emit({ phase: 'failed', errorCode: '' });
				});
		}, pollIntervalMs);
	}

	async function openOnce(ref: ExploreRef, articleId: string, retry: boolean): Promise<void> {
		const identity = generation;
		try {
			if (!retry) {
				const envelope = await options.lookup(articleId, ref);
				if (identity !== generation) return;
				if (envelope.status !== 'missing') {
					adopt(envelope);
					return;
				}
			}
			// A missing entry may be generated by this explicit click; an
			// explicit retry skips the lookup and requeues directly.
			// Replacement has its own regenerate path; this flow never
			// bypasses ready reuse, so it explicitly passes false.
			emit({ phase: 'queued' });
			const started = await options.start(articleId, {
				occurrence_id: ref.occurrenceId,
				annotation_id: ref.annotationId,
				retry,
				regenerate: false
			});
			if (identity !== generation) return;
			adopt(started);
		} catch {
			if (identity !== generation) return;
			emit({ phase: 'failed', errorCode: '' });
		}
	}

	return {
		get state(): ExploreState {
			return state;
		},
		// open resolves the saved state for one subject; the returned promise
		// settles after the flow reaches a pending or terminal state so
		// callers can reposition the popover.
		open(ref: ExploreRef, articleId: string, retry = false): Promise<void> {
			generation += 1;
			clearTimer();
			state = { ...initialExploreState };
			options.onChange(state);
			return openOnce(ref, articleId, retry);
		},
		retry(ref: ExploreRef, articleId: string): Promise<void> {
			return this.open(ref, articleId, true);
		},
		// regenerate starts a fresh request under the current active
		// profile and bypasses ready reuse. The saved document stays on
		// screen until the replacement commits; a duplicate call while
		// pending rejoins the same generation instead of starting another.
		regenerate(ref: ExploreRef, articleId: string): Promise<void> {
			if (state.phase === 'queued' || state.phase === 'generating') return Promise.resolve();
			generation += 1;
			clearTimer();
			const identity = generation;
			emit({ phase: 'queued', errorCode: '', generationErrorCode: '' });
			return (async () => {
				try {
					const started = await options.start(articleId, {
						occurrence_id: ref.occurrenceId,
						annotation_id: ref.annotationId,
						retry: false,
						regenerate: true
					});
					if (identity !== generation) return;
					adopt(started);
				} catch {
					if (identity !== generation) return;
					emit({ phase: 'failed', errorCode: '' });
				}
			})();
		},
		close(): void {
			generation += 1;
			clearTimer();
			state = { ...initialExploreState };
			options.onChange(state);
		}
	};
}
