package auth

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"strings"
	"time"
)

const (
	// CSRFTokenBytes is the number of random bytes in a CSRF token.
	CSRFTokenBytes = 32

	// CSRFHeader is the HTTP header that carries the CSRF token for state-changing requests.
	CSRFHeader = "X-CSRF-Token"

	// CSRFCookie is the name of the CSRF cookie (readable by JavaScript).
	CSRFCookie = "csrf_token"

	// CSRFMaxAge is the lifetime of a CSRF cookie.
	CSRFMaxAge = 12 * time.Hour
)

// CSRF generates and validates anti-CSRF tokens via the double-submit cookie
// pattern. The secret binds tokens to the server instance.
type CSRF struct {
	secret []byte
}

// NewCSRF returns a CSRF protector keyed with the provided secret.
func NewCSRF(secret []byte) *CSRF {
	return &CSRF{secret: secret}
}

// GenerateToken produces a random token and an HMAC of that token keyed with
// the CSRF secret. The returned value is base64url-encoded.
func (c *CSRF) GenerateToken() (string, error) {
	raw := make([]byte, CSRFTokenBytes)
	if _, err := rand.Read(raw); err != nil {
		return "", fmt.Errorf("generate csrf token: %w", err)
	}
	mac := hmac.New(sha256.New, c.secret)
	mac.Write(raw)
	signed := append(raw, mac.Sum(nil)...)
	return base64.RawURLEncoding.EncodeToString(signed), nil
}

// ValidateToken checks that the submitted token was generated by this CSRF
// protector (HMAC verifies) and is not a replay of another token via
// constant-time comparison.
func (c *CSRF) ValidateToken(token string) bool {
	if token == "" {
		return false
	}
	decoded, err := base64.RawURLEncoding.DecodeString(token)
	if err != nil {
		return false
	}
	if len(decoded) < CSRFTokenBytes+sha256.Size {
		return false
	}
	raw := decoded[:CSRFTokenBytes]
	receivedMAC := decoded[CSRFTokenBytes:]
	expectedMAC := hmac.New(sha256.New, c.secret)
	expectedMAC.Write(raw)
	return hmac.Equal(receivedMAC, expectedMAC.Sum(nil))
}

// SetCookie writes the CSRF cookie to the response. The cookie is NOT HTTPOnly
// so JavaScript can read it for the custom header, but it is SameSite strict.
func (c *CSRF) SetCookie(w http.ResponseWriter, token string, secure bool) {
	http.SetCookie(w, &http.Cookie{
		Name:     CSRFCookie,
		Value:    token,
		Path:     "/",
		MaxAge:   int(CSRFMaxAge.Seconds()),
		HttpOnly: false, // JavaScript must read this for the X-CSRF-Token header.
		Secure:   secure,
		SameSite: http.SameSiteStrictMode,
	})
}

// VerifyRequest validates the CSRF token from the request header against the
// cookie. This implements the double-submit cookie pattern.
func (c *CSRF) VerifyRequest(r *http.Request) error {
	if r.Method == http.MethodGet || r.Method == http.MethodHead || r.Method == http.MethodOptions {
		return nil
	}
	cookie, err := r.Cookie(CSRFCookie)
	if err != nil {
		return errors.New("csrf: missing token cookie")
	}
	header := strings.TrimSpace(r.Header.Get(CSRFHeader))
	if header == "" {
		return errors.New("csrf: missing token header")
	}
	if !c.ValidateToken(cookie.Value) {
		return errors.New("csrf: invalid token cookie")
	}
	if !c.ValidateToken(header) {
		return errors.New("csrf: invalid token header")
	}
	// Both tokens are valid independently; now verify they match.
	if cookie.Value != header {
		return errors.New("csrf: token mismatch")
	}
	return nil
}
